"""
Django settings for django_autocompeter project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys

from decouple import config, Csv
from unipath import Path
import dj_database_url


BASE_DIR = Path(__file__).parent
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)
DEBUG_PROPAGATE_EXCEPTIONS = config(
    'DEBUG_PROPAGATE_EXCEPTIONS',
    False,
    cast=bool,
)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.postgres',

    'autocompeter.main',
    'autocompeter.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autocompeter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'autocompeter.wsgi.application'


DATABASES = {
    'default': config(
        'DATABASE_URL',
        # default='postgresql://localhost/autocompeter',
        # default='postgresql://postgres@0.0.0.0:5432/postgres',
        # default='postgresql://postgres@0.0.0.0:5432/postgres',
        default='postgres://postgres@db:5432/postgres',
        cast=dj_database_url.parse
    )
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'HOST': 'db',
#         'PORT': 5432,
#     }
# }
# WORKS: {'default': {'PORT': 5432, 'HOST': 'db', 'ENGINE': 'django.db.backends.postgresql', 'NAME': 'postgres', 'USER': 'postgres'}}
# FAILS: {'default': {'CONN_MAX_AGE': 0, 'PORT': 5432, 'NAME': 'postgres', 'ENGINE': 'django.db.backends.postgresql_psycopg2', 'PASSWORD': '', 'HOST': '', 'USER': 'postgres'}}
# print(DATABASES)

CACHES = {
    'default': {
        'BACKEND': config(
            'CACHE_BACKEND',
            'django.core.cache.backends.memcached.MemcachedCache',
        ),
        'LOCATION': config('CACHE_LOCATION', '127.0.0.1:11211'),
        'TIMEOUT': config('CACHE_TIMEOUT', 500),
        'KEY_PREFIX': config('CACHE_KEY_PREFIX', 'autocompeter'),
    }
}


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


# ElasticSearch

ES_INDEX = 'autocompeter'

ES_INDEX_SETTINGS = {
    'number_of_shards': 1,
    'number_of_replicas': 0,
}

ES_CONNECTIONS = {
    'default': {
        'hosts': ['elasticsearch:9200']
    },
}


if 'test' in sys.argv[1:2]:
    # os.environ['OPBEAT_DISABLE_SEND'] = 'true'
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
